name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.BURNOOK_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BURNOOK_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.MONVILLARIN_COM_REGIONS }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ vars.MONVILLARIN_COM_NAME }} --delete
